In [1]:
import pandas as pd
air25_data = pd.read_csv('cleaned_air4thai.csv')
air25_data

             DATETIMEDATA  PM25  WS  TEMP  RH  WD stationID
0     2023-12-01 00:00:00  32.6   1    30  53  49       02t
1     2023-12-01 01:00:00  40.5   1    30  55  51       02t
2     2023-12-01 02:00:00  33.8   0    29  57   5       02t
3     2023-12-01 03:00:00  33.7   0    29  60  30       02t
4     2023-12-01 04:00:00  36.0   1    28  62  19       02t
...                   ...   ...  ..   ...  ..  ..       ...
8539  2024-02-27 19:00:00  44.8   0     0   1   0       08t
8540  2024-02-27 20:00:00  39.9   0     0   1   0       08t
8541  2024-02-27 21:00:00  38.9   0     0   1   0       08t
8542  2024-02-27 22:00:00  39.0   0     0   1   0       08t
8543  2024-02-27 23:00:00  37.8   0     0   1   0       08t

[8544 rows x 7 columns]

In [3]:
import pandas as pd
from pycaret.regression import *

# อ่านข้อมูลจากไฟล์ CSV
data = pd.read_csv('cleaned_air4thai.csv')  # แทนที่ 'your_file.csv' ด้วยชื่อไฟล์ของคุณ

# สร้างโมเดล
exp1 = setup(data, target='PM25', session_id=123)

# เปรียบเทียบและเลือกโมเดลที่ดีที่สุด
best_model = compare_models()

# ปรับแต่งโมเดลที่ดีที่สุด
tuned_model = tune_model(best_model)

# ทำนายล่วงหน้า 7 วัน
future_data = data.copy()  # อาจต้องปรับข้อมูลที่ต้องการทำนายล่วงหน้า
future_predictions = predict_model(tuned_model, data=future_data, round=0)
print("อะไรนะบอกอีกที")
# แสดงผลลัพธ์
future_predictions

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

อะไรนะบอกอีกที

,DATETIMEDATA,O3,WS,TEMP,RH,WD,stationID,PM25,prediction_label
0,2024-01-01 00:00:00,16.0,1,27,79,115,44t,16.500000,16.500000
1,2024-01-01 01:00:00,0.0,1,27,82,97,44t,33.599998,33.599998
2,2024-01-01 02:00:00,0.0,1,26,84,96,44t,34.200001,34.200001
3,2024-01-01 03:00:00,0.0,1,26,82,108,44t,20.100000,20.100000
4,2024-01-01 04:00:00,1.0,1,27,79,106,44t,16.500000,16.500000
...,...,...,...,...,...,...,...,...,...
5563,2024-02-27 19:00:00,9.0,1,29,67,162,44t,21.700001,21.700001
5564,2024-02-27 20:00:00,1.0,1,29,68,134,44t,17.500000,17.500000
5565,2024-02-27 21:00:00,0.0,1,29,69,140,44t,21.100000,21.100000
5566,2024-02-27 22:00:00,0.0,1,29,70,111,44t,23.200001,23.200001
5567,2024-02-27 23:00:00,8.0,1,28,71,120,44t,16.200001,16.200001

In [8]:
import pandas as pd
from pycaret.regression import *
from datetime import datetime, timedelta

data = pd.read_csv('cleaned_air4thai.csv')

# สร้างโมเดล
exp1 = setup(data, target='PM25', session_id=123)

# เปรียบเทียบและเลือกโมเดลที่ดีที่สุด
best_model = compare_models()

# ปรับแต่งโมเดลที่ดีที่สุด
tuned_model = tune_model(best_model)

# ทำนายล่วงหน้า 7 วัน
future_data = data.copy()  # อาจต้องปรับข้อมูลที่ต้องการทำนายล่วงหน้า
future_predictions = predict_model(tuned_model, data=future_data, round=0)

# เรียงลำดับข้อมูล Categorical
future_data['DATETIMEDATA'] = pd.to_datetime(future_data['DATETIMEDATA'])
future_predictions['DATETIMEDATA'] = pd.to_datetime(future_predictions['DATETIMEDATA'])

# สร้างตารางที่มีข้อมูลเฉพาะของวันที่ 7 วันนี้
today = datetime.now().strftime('%Y-%m-%d')
future_data_7_days = future_data[future_data['DATETIMEDATA'] >= today].sort_values('DATETIMEDATA')
future_predictions_7_days = future_predictions[future_predictions['DATETIMEDATA'] >= today].sort_values('DATETIMEDATA')


# print("ข้อมูลที่นำมาทำนายล่วงหน้า 7 วัน:")
# print(future_data_7_days)

# print("\nผลลัพธ์การทำนายล่วงหน้า 7 วัน:")
# print(future_predictions_7_days)
future_data_7_days
future_predictions_7_days

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Empty DataFrame
Columns: [DATETIMEDATA, O3, WS, TEMP, RH, WD, stationID, PM25, prediction_label]
Index: []

In [1]:
from pycaret.regression import *
import pandas as pd

# โหลดข้อมูลที่คุณคลีนแล้ว
data = pd.read_csv('cleaned_air4thai.csv')

# ตรวจสอบว่ามีคอลัมน์ 'DATETIMEDATA' ในข้อมูลหรือไม่
if 'DATETIMEDATA' in data.columns:
    # แปลงคอลัมน์ DATETIMEDATA ให้เป็น datetime
    data['DATETIMEDATA'] = pd.to_datetime(data['DATETIMEDATA'])
    
    # สร้างคอลัมน์ใหม่
    data['hour'] = data['DATETIMEDATA'].dt.hour
    data['day_of_week'] = data['DATETIMEDATA'].dt.dayofweek
    data['day'] = data['DATETIMEDATA'].dt.day
    data['month'] = data['DATETIMEDATA'].dt.month
else:
    print("Column 'DATETIMEDATA' not found in the dataset. Please check your dataset.")

# ตั้งค่าสภาพแวดล้อม PyCaret
exp_reg = setup(data=data, target='PM25', session_id=123,
                ignore_features=['DATETIMEDATA', 'PM10', 'O3', 'CO', 'NO2', 'SO2', 'WS', 'TEMP', 'RH', 'WD'],
                numeric_features=['hour', 'day_of_week', 'day', 'month'])

# เปรียบเทียบโมเดล
best_model = compare_models()

# สร้างโมเดล
created_model = create_model(best_model)

# ปรับแต่งโมเดล
tuned_model = tune_model(created_model)

# ประเมินโมเดล
evaluate_model(tuned_model)

# บันทึกโมเดล
save_model(tuned_model, 'final_pm25_prediction_model')

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['hour', 'day_of_week', 'day',
                                              'month'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['stationID'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['stationID'],
                                     transformer=OneHotEncoder(cols=['stationID'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('trained_model',
                  ExtraTreesRegressor(n_jobs=-1, random_state=123))]),
 'final_pm25_prediction_model.pkl')